apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::444152781209:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-cES5FqOQY30P
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::444152781209:user/bunny
      username: bunny
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-14T14:35:00Z"
  name: aws-auth
  namespace: kube-system
  uid: cf2cb3d9-42ff-4783-9f8e-ca3112a28a05